source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'ARCore/GARSession', '~> 1.35.0'
  pod 'ARCore/Geospatial', '~> 1.35.0'
end
target 'Unity-iPhone' do
end
use_frameworks!
